"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { useMeetingFlow } from "@/components/meeting/meeting-context";
import { MomRenderer } from "@/components/meeting/mom-renderer";
import { generateMom } from "@/actions/generate-mom";

export default function MomViewerPage() {
  const router = useRouter();
  const { meetingData, meetingId } = useMeetingFlow();

  const [step, setStep] = useState<"generating" | "view">("generating");
  const [progress, setProgress] = useState(0);
  const [momData, setMomData] = useState<any>(null);
  const [momText, setMomText] = useState("");
  const [editing, setEditing] = useState(false);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (step !== "generating") return;

    const generate = async () => {
      if (!meetingData?.transcript) {
        setError("No transcript available");
        setStep("view");
        return;
      }

      const iv = setInterval(() => {
        setProgress((p) => {
          if (p >= 90) {
            clearInterval(iv);
            return 90;
          }
          return p + Math.random() * 8 + 2;
        });
      }, 200);

      try {
        const result = await generateMom(
          meetingData.transcript,
          meetingData.title || "Meeting",
          meetingData.participants || "",
          meetingData.agenda || "",
        );

        clearInterval(iv);
        setProgress(100);

        if (result.success && result.mom) {
          setMomData(result.mom);
          const formatted = formatMomText(result.mom);
          setMomText(formatted);
          setTimeout(() => setStep("view"), 500);
        } else {
          setError("Unable to generate meeting summary. Please try again later.");
          setStep("view");
        }
      } catch (err) {
        clearInterval(iv);
        setError("AI service temporarily unavailable. Please try again later.");
        setStep("view");
      }
    };

    generate();
  }, [step, meetingData]);

  const copy = () => {
    navigator.clipboard?.writeText(momText.replace(/\*\*/g, ""));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const formatMomText = (data: any): string => {
    if (!data) return "";
    
    let text = `# Minutes of Meeting\n\n`;
    text += `**Executive Summary**\n${data.executive_summary || ""}\n\n`;
    text += `## Meeting Summary\n${data.meeting_summary || ""}\n\n`;
    text += `## Key Highlights\n`;
    if (data.highlights?.length) {
      data.highlights.forEach((h: string) => {
        text += `- ${h}\n`;
      });
    }
    text += `\n## Decisions\n`;
    if (data.decisions?.length) {
      data.decisions.forEach((d: string) => {
        text += `- ${d}\n`;
      });
    }
    text += `\n## Action Items\n`;
    if (data.action_items?.length) {
      data.action_items.forEach((item: any) => {
        text += `- [ ] ${item.task} (Assignee: ${item.owner}${item.deadline ? `, Due: ${item.deadline}` : ""})\n`;
      });
    }
    text += `\n## Risks\n`;
    if (data.risks?.length) {
      data.risks.forEach((r: string) => {
        text += `- ${r}\n`;
      });
    }
    text += `\n## Standard Operating Procedure\n`;
    if (data.sop?.length) {
      data.sop.forEach((s: string) => {
        text += `${s}\n`;
      });
    }
    
    return text;
  };

  const handleSave = () => {
    router.push("/dashboard");
  };

  if (step === "generating") {
    return (
      <div className="min-h-[80vh] flex items-center justify-center px-6">
        <div className="text-center max-w-lg w-full">
          <div className="text-[clamp(3rem,8vw,5rem)] font-bold uppercase leading-none text-primary mb-6">
            Generating
          </div>
          <p className="text-xl text-muted-foreground mb-8">
            AI is composing your meeting minutes
          </p>
          <Progress value={progress} className="h-2 mb-3" />
          <p className="font-bold text-primary font-mono text-lg">
            {Math.round(progress)}%
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="w-full px-6 md:px-12 py-12 md:py-20 min-h-screen flex flex-col">
      <div className="max-w-4xl mx-auto w-full flex flex-col flex-1">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-end mb-8 gap-6 shrink-0">
          <div>
            <div className="text-[clamp(2rem,6vw,4rem)] font-bold uppercase leading-[0.85] tracking-tighter mb-2">
              Minutes of Meeting
            </div>
            <p className="text-lg text-muted-foreground">
              Generated by AI · Ready to save or export
            </p>
          </div>

          <div className="flex items-center gap-3">
            <Button
              variant="outline"
              size="sm"
              onClick={() => setEditing(!editing)}
            >
              {editing ? "Preview" : "Edit"}
            </Button>
            <Button variant="outline" size="sm" onClick={copy}>
              {copied ? "Copied!" : "Copy"}
            </Button>
            <Button onClick={handleSave} size="sm">
              Save to Archive
            </Button>
          </div>
        </div>

        <div className="flex-1 border-2 border-border p-8 min-h-[600px]">
          {editing ? (
            <Textarea
              value={momText}
              onChange={(e) => setMomText(e.target.value)}
              className="w-full h-full min-h-[500px] border-none p-0 text-lg leading-relaxed resize-none"
            />
          ) : (
            <MomRenderer text={momText} />
          )}
        </div>
      </div>
    </div>
  );
}
