"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { useMeetingFlow } from "@/components/meeting/meeting-context";
import { MomRenderer } from "@/components/meeting/mom-renderer";
import { MOCK_MOM } from "@/lib/mock-data";

export default function MomViewerPage() {
  const router = useRouter();
  const { meetingData, meetingId } = useMeetingFlow();

  const [step, setStep] = useState<"generating" | "view">("generating");
  const [progress, setProgress] = useState(0);
  const [momText, setMomText] = useState("");
  const [editing, setEditing] = useState(false);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (step !== "generating") return;
    const iv = setInterval(() => {
      setProgress((p) => {
        if (p >= 100) {
          clearInterval(iv);
          setMomText(MOCK_MOM(meetingData || {}));
          setStep("view");
          return 100;
        }
        return p + Math.random() * 10 + 3;
      });
    }, 180);
    return () => clearInterval(iv);
  }, [step, meetingData]);

  const copy = () => {
    navigator.clipboard?.writeText(momText.replace(/\*\*/g, ""));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSave = () => {
    router.push("/dashboard");
  };

  if (step === "generating") {
    return (
      <div className="min-h-[80vh] flex items-center justify-center px-6">
        <div className="text-center max-w-lg w-full">
          <div className="text-[clamp(3rem,8vw,5rem)] font-bold uppercase leading-none text-primary mb-6">
            Generating
          </div>
          <p className="text-xl text-muted-foreground mb-8">
            AI is composing your meeting minutes
          </p>
          <Progress value={progress} className="h-2 mb-3" />
          <p className="font-bold text-primary font-mono text-lg">
            {Math.round(progress)}%
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="w-full px-6 md:px-12 py-12 md:py-20 min-h-screen flex flex-col">
      <div className="max-w-4xl mx-auto w-full flex flex-col flex-1">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-end mb-8 gap-6 shrink-0">
          <div>
            <div className="text-[clamp(2rem,6vw,4rem)] font-bold uppercase leading-[0.85] tracking-tighter mb-2">
              Minutes of Meeting
            </div>
            <p className="text-lg text-muted-foreground">
              Generated by AI · Ready to save or export
            </p>
          </div>

          <div className="flex items-center gap-3">
            <Button
              variant="outline"
              size="sm"
              onClick={() => setEditing(!editing)}
            >
              {editing ? "Preview" : "Edit"}
            </Button>
            <Button variant="outline" size="sm" onClick={copy}>
              {copied ? "Copied!" : "Copy"}
            </Button>
            <Button onClick={handleSave} size="sm">
              Save to Archive
            </Button>
          </div>
        </div>

        <div className="flex-1 border-2 border-border p-8 min-h-[600px]">
          {editing ? (
            <Textarea
              value={momText}
              onChange={(e) => setMomText(e.target.value)}
              className="w-full h-full min-h-[500px] border-none p-0 text-lg leading-relaxed resize-none"
            />
          ) : (
            <MomRenderer text={momText} />
          )}
        </div>
      </div>
    </div>
  );
}
